// Generated by gencpp from file ps4_bot/AddtwoIntsRequest.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_ADDTWOINTSREQUEST_H
#define PS4_BOT_MESSAGE_ADDTWOINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ps4_bot
{
template <class ContainerAllocator>
struct AddtwoIntsRequest_
{
  typedef AddtwoIntsRequest_<ContainerAllocator> Type;

  AddtwoIntsRequest_()
    : a(0)
    , b(0)  {
    }
  AddtwoIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;





  typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddtwoIntsRequest_

typedef ::ps4_bot::AddtwoIntsRequest_<std::allocator<void> > AddtwoIntsRequest;

typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsRequest > AddtwoIntsRequestPtr;
typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsRequest const> AddtwoIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator1> & lhs, const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator1> & lhs, const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ps4_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "36d09b846be0b371c5f190354dd3153e";
  }

  static const char* value(const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x36d09b846be0b371ULL;
  static const uint64_t static_value2 = 0xc5f190354dd3153eULL;
};

template<class ContainerAllocator>
struct DataType< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ps4_bot/AddtwoIntsRequest";
  }

  static const char* value(const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
;
  }

  static const char* value(const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddtwoIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ps4_bot::AddtwoIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PS4_BOT_MESSAGE_ADDTWOINTSREQUEST_H
