// Generated by gencpp from file ps4_bot/AddtwoIntsResponse.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_ADDTWOINTSRESPONSE_H
#define PS4_BOT_MESSAGE_ADDTWOINTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ps4_bot
{
template <class ContainerAllocator>
struct AddtwoIntsResponse_
{
  typedef AddtwoIntsResponse_<ContainerAllocator> Type;

  AddtwoIntsResponse_()
    : sum(0)  {
    }
  AddtwoIntsResponse_(const ContainerAllocator& _alloc)
    : sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AddtwoIntsResponse_

typedef ::ps4_bot::AddtwoIntsResponse_<std::allocator<void> > AddtwoIntsResponse;

typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsResponse > AddtwoIntsResponsePtr;
typedef boost::shared_ptr< ::ps4_bot::AddtwoIntsResponse const> AddtwoIntsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator1> & lhs, const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sum == rhs.sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator1> & lhs, const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ps4_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88405221c77b1878a3cbbfff53428d7";
  }

  static const char* value(const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88405221c77b187ULL;
  static const uint64_t static_value2 = 0x8a3cbbfff53428d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ps4_bot/AddtwoIntsResponse";
  }

  static const char* value(const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 sum\n"
;
  }

  static const char* value(const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddtwoIntsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ps4_bot::AddtwoIntsResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PS4_BOT_MESSAGE_ADDTWOINTSRESPONSE_H
