// Generated by gencpp from file ps4_bot/GpsCompassRequest.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_GPSCOMPASSREQUEST_H
#define PS4_BOT_MESSAGE_GPSCOMPASSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace ps4_bot
{
template <class ContainerAllocator>
struct GpsCompassRequest_
{
  typedef GpsCompassRequest_<ContainerAllocator> Type;

  GpsCompassRequest_()
    : request()  {
    }
  GpsCompassRequest_(const ContainerAllocator& _alloc)
    : request(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GpsCompassRequest_

typedef ::ps4_bot::GpsCompassRequest_<std::allocator<void> > GpsCompassRequest;

typedef boost::shared_ptr< ::ps4_bot::GpsCompassRequest > GpsCompassRequestPtr;
typedef boost::shared_ptr< ::ps4_bot::GpsCompassRequest const> GpsCompassRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ps4_bot::GpsCompassRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ps4_bot::GpsCompassRequest_<ContainerAllocator1> & lhs, const ::ps4_bot::GpsCompassRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ps4_bot::GpsCompassRequest_<ContainerAllocator1> & lhs, const ::ps4_bot::GpsCompassRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ps4_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57c42d82c9bab8a1ec9de111b7540471";
  }

  static const char* value(const ::ps4_bot::GpsCompassRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57c42d82c9bab8a1ULL;
  static const uint64_t static_value2 = 0xec9de111b7540471ULL;
};

template<class ContainerAllocator>
struct DataType< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ps4_bot/GpsCompassRequest";
  }

  static const char* value(const ::ps4_bot::GpsCompassRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Empty msg for request\n"
"std_msgs/Empty request\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Empty\n"
;
  }

  static const char* value(const ::ps4_bot::GpsCompassRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsCompassRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ps4_bot::GpsCompassRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ps4_bot::GpsCompassRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PS4_BOT_MESSAGE_GPSCOMPASSREQUEST_H
