// Generated by gencpp from file ps4_bot/GpsCompass.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_GPSCOMPASS_H
#define PS4_BOT_MESSAGE_GPSCOMPASS_H

#include <ros/service_traits.h>


#include <ps4_bot/GpsCompassRequest.h>
#include <ps4_bot/GpsCompassResponse.h>


namespace ps4_bot
{

struct GpsCompass
{

typedef GpsCompassRequest Request;
typedef GpsCompassResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GpsCompass
} // namespace ps4_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ps4_bot::GpsCompass > {
  static const char* value()
  {
    return "b232e5ea178ff58767787805c24ec2f6";
  }

  static const char* value(const ::ps4_bot::GpsCompass&) { return value(); }
};

template<>
struct DataType< ::ps4_bot::GpsCompass > {
  static const char* value()
  {
    return "ps4_bot/GpsCompass";
  }

  static const char* value(const ::ps4_bot::GpsCompass&) { return value(); }
};


// service_traits::MD5Sum< ::ps4_bot::GpsCompassRequest> should match
// service_traits::MD5Sum< ::ps4_bot::GpsCompass >
template<>
struct MD5Sum< ::ps4_bot::GpsCompassRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ps4_bot::GpsCompass >::value();
  }
  static const char* value(const ::ps4_bot::GpsCompassRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ps4_bot::GpsCompassRequest> should match
// service_traits::DataType< ::ps4_bot::GpsCompass >
template<>
struct DataType< ::ps4_bot::GpsCompassRequest>
{
  static const char* value()
  {
    return DataType< ::ps4_bot::GpsCompass >::value();
  }
  static const char* value(const ::ps4_bot::GpsCompassRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ps4_bot::GpsCompassResponse> should match
// service_traits::MD5Sum< ::ps4_bot::GpsCompass >
template<>
struct MD5Sum< ::ps4_bot::GpsCompassResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ps4_bot::GpsCompass >::value();
  }
  static const char* value(const ::ps4_bot::GpsCompassResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ps4_bot::GpsCompassResponse> should match
// service_traits::DataType< ::ps4_bot::GpsCompass >
template<>
struct DataType< ::ps4_bot::GpsCompassResponse>
{
  static const char* value()
  {
    return DataType< ::ps4_bot::GpsCompass >::value();
  }
  static const char* value(const ::ps4_bot::GpsCompassResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PS4_BOT_MESSAGE_GPSCOMPASS_H
