// Generated by gencpp from file ps4_bot/GpsCompassResponse.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_GPSCOMPASSRESPONSE_H
#define PS4_BOT_MESSAGE_GPSCOMPASSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geographic_msgs/GeoPoint.h>

namespace ps4_bot
{
template <class ContainerAllocator>
struct GpsCompassResponse_
{
  typedef GpsCompassResponse_<ContainerAllocator> Type;

  GpsCompassResponse_()
    : position()
    , angle(0.0)  {
    }
  GpsCompassResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GpsCompassResponse_

typedef ::ps4_bot::GpsCompassResponse_<std::allocator<void> > GpsCompassResponse;

typedef boost::shared_ptr< ::ps4_bot::GpsCompassResponse > GpsCompassResponsePtr;
typedef boost::shared_ptr< ::ps4_bot::GpsCompassResponse const> GpsCompassResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ps4_bot::GpsCompassResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ps4_bot::GpsCompassResponse_<ContainerAllocator1> & lhs, const ::ps4_bot::GpsCompassResponse_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ps4_bot::GpsCompassResponse_<ContainerAllocator1> & lhs, const ::ps4_bot::GpsCompassResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ps4_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d2cef402af49fe31c4825156ee1a6e2";
  }

  static const char* value(const ::ps4_bot::GpsCompassResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d2cef402af49fe3ULL;
  static const uint64_t static_value2 = 0x1c4825156ee1a6e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ps4_bot/GpsCompassResponse";
  }

  static const char* value(const ::ps4_bot::GpsCompassResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"#current position of client\n"
"geographic_msgs/GeoPoint position\n"
"\n"
"#current orientation based on compass North(degree)\n"
"float64 angle\n"
"\n"
"================================================================================\n"
"MSG: geographic_msgs/GeoPoint\n"
"# Geographic point, using the WGS 84 reference ellipsoid.\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south\n"
"# (-90 <= latitude <= +90).\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is\n"
"# west (-180 <= longitude <= +180). At the poles, latitude is -90 or\n"
"# +90, and longitude is irrelevant, but must be in range.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).\n"
"float64 altitude\n"
;
  }

  static const char* value(const ::ps4_bot::GpsCompassResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GpsCompassResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ps4_bot::GpsCompassResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ps4_bot::GpsCompassResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PS4_BOT_MESSAGE_GPSCOMPASSRESPONSE_H
