// Generated by gencpp from file ps4_bot/Navigation.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_NAVIGATION_H
#define PS4_BOT_MESSAGE_NAVIGATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geographic_msgs/GeoPoint.h>
#include <geographic_msgs/GeoPoint.h>
#include <geographic_msgs/BoundingBox.h>
#include <geographic_msgs/GeoPoint.h>
#include <ps4_bot/vertices.h>

namespace ps4_bot
{
template <class ContainerAllocator>
struct Navigation_
{
  typedef Navigation_<ContainerAllocator> Type;

  Navigation_()
    : start()
    , goal()
    , boundary()
    , center()
    , polygons()
    , navigation_status(false)  {
    }
  Navigation_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)
    , boundary(_alloc)
    , center(_alloc)
    , polygons(_alloc)
    , navigation_status(false)  {
  (void)_alloc;
    }



   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef  ::geographic_msgs::BoundingBox_<ContainerAllocator>  _boundary_type;
  _boundary_type boundary;

   typedef  ::geographic_msgs::GeoPoint_<ContainerAllocator>  _center_type;
  _center_type center;

   typedef std::vector< ::ps4_bot::vertices_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ps4_bot::vertices_<ContainerAllocator> >::other >  _polygons_type;
  _polygons_type polygons;

   typedef uint8_t _navigation_status_type;
  _navigation_status_type navigation_status;





  typedef boost::shared_ptr< ::ps4_bot::Navigation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ps4_bot::Navigation_<ContainerAllocator> const> ConstPtr;

}; // struct Navigation_

typedef ::ps4_bot::Navigation_<std::allocator<void> > Navigation;

typedef boost::shared_ptr< ::ps4_bot::Navigation > NavigationPtr;
typedef boost::shared_ptr< ::ps4_bot::Navigation const> NavigationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ps4_bot::Navigation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ps4_bot::Navigation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ps4_bot::Navigation_<ContainerAllocator1> & lhs, const ::ps4_bot::Navigation_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.goal == rhs.goal &&
    lhs.boundary == rhs.boundary &&
    lhs.center == rhs.center &&
    lhs.polygons == rhs.polygons &&
    lhs.navigation_status == rhs.navigation_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ps4_bot::Navigation_<ContainerAllocator1> & lhs, const ::ps4_bot::Navigation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ps4_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::Navigation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::Navigation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::Navigation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::Navigation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::Navigation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::Navigation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ps4_bot::Navigation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "135fcffa3e2b8bd004214e3d13184e74";
  }

  static const char* value(const ::ps4_bot::Navigation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x135fcffa3e2b8bd0ULL;
  static const uint64_t static_value2 = 0x04214e3d13184e74ULL;
};

template<class ContainerAllocator>
struct DataType< ::ps4_bot::Navigation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ps4_bot/Navigation";
  }

  static const char* value(const ::ps4_bot::Navigation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ps4_bot::Navigation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#Recording the start and goal of the navigation\n"
"\n"
"#lat lng of start position\n"
"geographic_msgs/GeoPoint start\n"
"\n"
"#lat lng of goal position\n"
"geographic_msgs/GeoPoint goal\n"
"\n"
"#boundary of control zone\n"
"#min SW\n"
"#max NE\n"
"geographic_msgs/BoundingBox boundary\n"
"geographic_msgs/GeoPoint center\n"
"\n"
"#list of vertices\n"
"ps4_bot/vertices[] polygons\n"
"\n"
"bool navigation_status\n"
"\n"
"================================================================================\n"
"MSG: geographic_msgs/GeoPoint\n"
"# Geographic point, using the WGS 84 reference ellipsoid.\n"
"\n"
"# Latitude [degrees]. Positive is north of equator; negative is south\n"
"# (-90 <= latitude <= +90).\n"
"float64 latitude\n"
"\n"
"# Longitude [degrees]. Positive is east of prime meridian; negative is\n"
"# west (-180 <= longitude <= +180). At the poles, latitude is -90 or\n"
"# +90, and longitude is irrelevant, but must be in range.\n"
"float64 longitude\n"
"\n"
"# Altitude [m]. Positive is above the WGS 84 ellipsoid (NaN if unspecified).\n"
"float64 altitude\n"
"\n"
"================================================================================\n"
"MSG: geographic_msgs/BoundingBox\n"
"# Geographic map bounding box. \n"
"#\n"
"# The two GeoPoints denote diagonally opposite corners of the box.\n"
"#\n"
"# If min_pt.latitude is NaN, the bounding box is \"global\", matching\n"
"# any valid latitude, longitude and altitude.\n"
"#\n"
"# If min_pt.altitude is NaN, the bounding box is two-dimensional and\n"
"# matches any altitude within the specified latitude and longitude\n"
"# range.\n"
"\n"
"GeoPoint min_pt         # lowest and most Southwestern corner\n"
"GeoPoint max_pt         # highest and most Northeastern corner\n"
"\n"
"================================================================================\n"
"MSG: ps4_bot/vertices\n"
"#list of GeoPoint\n"
"geographic_msgs/GeoPoint[] vertices\n"
;
  }

  static const char* value(const ::ps4_bot::Navigation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ps4_bot::Navigation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
      stream.next(m.boundary);
      stream.next(m.center);
      stream.next(m.polygons);
      stream.next(m.navigation_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Navigation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ps4_bot::Navigation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ps4_bot::Navigation_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "boundary: ";
    s << std::endl;
    Printer< ::geographic_msgs::BoundingBox_<ContainerAllocator> >::stream(s, indent + "  ", v.boundary);
    s << indent << "center: ";
    s << std::endl;
    Printer< ::geographic_msgs::GeoPoint_<ContainerAllocator> >::stream(s, indent + "  ", v.center);
    s << indent << "polygons[]" << std::endl;
    for (size_t i = 0; i < v.polygons.size(); ++i)
    {
      s << indent << "  polygons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ps4_bot::vertices_<ContainerAllocator> >::stream(s, indent + "    ", v.polygons[i]);
    }
    s << indent << "navigation_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.navigation_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PS4_BOT_MESSAGE_NAVIGATION_H
