// Generated by gencpp from file ps4_bot/processing_navResponse.msg
// DO NOT EDIT!


#ifndef PS4_BOT_MESSAGE_PROCESSING_NAVRESPONSE_H
#define PS4_BOT_MESSAGE_PROCESSING_NAVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Empty.h>

namespace ps4_bot
{
template <class ContainerAllocator>
struct processing_navResponse_
{
  typedef processing_navResponse_<ContainerAllocator> Type;

  processing_navResponse_()
    : response()  {
    }
  processing_navResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Empty_<ContainerAllocator>  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::ps4_bot::processing_navResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ps4_bot::processing_navResponse_<ContainerAllocator> const> ConstPtr;

}; // struct processing_navResponse_

typedef ::ps4_bot::processing_navResponse_<std::allocator<void> > processing_navResponse;

typedef boost::shared_ptr< ::ps4_bot::processing_navResponse > processing_navResponsePtr;
typedef boost::shared_ptr< ::ps4_bot::processing_navResponse const> processing_navResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ps4_bot::processing_navResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ps4_bot::processing_navResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ps4_bot::processing_navResponse_<ContainerAllocator1> & lhs, const ::ps4_bot::processing_navResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ps4_bot::processing_navResponse_<ContainerAllocator1> & lhs, const ::ps4_bot::processing_navResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ps4_bot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ps4_bot::processing_navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ps4_bot::processing_navResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ps4_bot::processing_navResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f624545799d912fd57177cf7069e330d";
  }

  static const char* value(const ::ps4_bot::processing_navResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf624545799d912fdULL;
  static const uint64_t static_value2 = 0x57177cf7069e330dULL;
};

template<class ContainerAllocator>
struct DataType< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ps4_bot/processing_navResponse";
  }

  static const char* value(const ::ps4_bot::processing_navResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"std_msgs/Empty response\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Empty\n"
;
  }

  static const char* value(const ::ps4_bot::processing_navResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct processing_navResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ps4_bot::processing_navResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ps4_bot::processing_navResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    s << std::endl;
    Printer< ::std_msgs::Empty_<ContainerAllocator> >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PS4_BOT_MESSAGE_PROCESSING_NAVRESPONSE_H
