(cl:defpackage ps4_bot-srv
  (:use )
  (:export
   "GPSCOMPASS"
   "<GPSCOMPASS-REQUEST>"
   "GPSCOMPASS-REQUEST"
   "<GPSCOMPASS-RESPONSE>"
   "GPSCOMPASS-RESPONSE"
   "NAVIGATION"
   "<NAVIGATION-REQUEST>"
   "NAVIGATION-REQUEST"
   "<NAVIGATION-RESPONSE>"
   "NAVIGATION-RESPONSE"
   "PROCESSING_NAV"
   "<PROCESSING_NAV-REQUEST>"
   "PROCESSING_NAV-REQUEST"
   "<PROCESSING_NAV-RESPONSE>"
   "PROCESSING_NAV-RESPONSE"
  ))

