(cl:defpackage ps4_bot-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "NAVIGATION"
   "<NAVIGATION-REQUEST>"
   "NAVIGATION-REQUEST"
   "<NAVIGATION-RESPONSE>"
   "NAVIGATION-RESPONSE"
  ))

